# Generated by Django 4.1.6 on 2023-03-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='documentoemp',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('numero_identificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipodocumentosemp',
            },
        ),
        migrations.CreateModel(
            name='insertempl',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(max_length=100)),
                ('documento_identificacion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('departamento', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=100)),
                ('fecha_contratacion', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='insertuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
