# Generated by Django 4.1.6 on 2023-03-10 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id_departamento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='documentoemp',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('numero_identificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipodocumentosemp',
            },
        ),
        migrations.CreateModel(
            name='insertuser',
            fields=[
                ('id_usuario', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'ACTIVO'), ('Inactivo', 'INACTIVO')], max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='puesto',
            fields=[
                ('puesto_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'puesto',
            },
        ),
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('direccion_sucursal', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='insertempl',
            fields=[
                ('id_empleado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('departamentos', models.CharField(max_length=50)),
                ('puestos', models.CharField(max_length=100)),
                ('sucursales', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantwebsite.departamento')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantwebsite.puesto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantwebsite.sucursal')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
