# Generated by Django 4.1.6 on 2023-03-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=50)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='restaurantwebsite.departamento')),
                ('pu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='restaurantwebsite.puesto')),
                ('sucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucu', to='restaurantwebsite.sucursal')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.DeleteModel(
            name='insertempl',
        ),
    ]
